name: Feature - Typing indicators
description: Show when peers are typing
labels: ["feature", "UX"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Display typing status for connected peers.
  - type: input
    id: goal
    attributes:
      label: Goal
      value: Show typing indicators
  - type: textarea
    id: approach
    attributes:
      label: Proposed Approach
      description: How should this work?
      placeholder: Send typing events via data channel with debouncing.
  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      options:
        - label: Detect typing activity
        - label: Send typing status via data channel
        - label: Display typing indicator
        - label: Auto-clear after timeout
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - Indicator shows when peer types
        - Clears when typing stops
        - Minimal data channel usage
